name: ecc
version: 1.0.0+1
publish_to: none
description: Encontro de Casais com Cristo
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^4.6.0
  google_sign_in: ^6.1.0
  icons_plus: ^4.0.0
  social_login_buttons: ^1.0.7
  flutter_boom_menu_new: ^1.0.1
  cloud_firestore: ^4.7.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.0
  flutter_slidable: ^3.0.0
  scrollable_text_indicator: ^0.0.2
  flip_card: ^0.7.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  flutter_fast_forms: ^11.0.0
  mask_text_input_formatter: ^2.4.0
  dio2: ^5.0.0-nullsafety
  slide_popup_dialog_null_safety: ^1.0.0
  encryptor: ^0.0.1
  art_sweetalert: ^0.0.5
  searchable_listview: ^2.4.0
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
